//auth screen
export const LOGIN_SCREEN = "[LOGIN MODULE SCREEN] LOGIN";
export const REGISTER_SCREEN = "[REGISTER MODULE SCREEN REGISTER";
//main screen
export const MAIN_SCREEN = "[MAIN SCREEN] MAIN";
//chat screen
export const CHAT_LIST_SCREEN = "[CHAT MODULE SCREEN] CHAT LIST";
export const CHAT_DETAIL_SCREEN = "[CHAT MODULE SCREEN] CHAT DETAIL";
//profile
export const PROFILE_INFO_SCREEN = "[PROFILE MODULE SCREEN] PROFILE INFO";
export const PROFILE_MODAL_SCREEN = "[PROFILE MODULE SCREEN] PROFILE MODAL";